# Generated by Django 4.0.2 on 2022-02-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_and_villains', '0002_alter_supers_super_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_type_id',
            new_name='super_type',
        ),
    ]
