# Generated by Django 4.0.2 on 2022-02-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_heroes_or_villains', '0010_rename_alignment_type_super_type_alignment'),
        ('heroes_and_villains', '0003_rename_super_type_id_supers_super_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supers',
            new_name='Super',
        ),
    ]
