# Generated by Django 4.0.2 on 2022-02-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_and_villains', '0004_rename_supers_super'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='super_type_id',
        ),
    ]
