# Generated by Django 4.0.2 on 2022-02-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_and_villains', '0005_rename_super_type_super_super_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type_id',
            new_name='super_type',
        ),
    ]
