# Generated by Django 4.0.2 on 2022-02-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_heroes_or_villains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_type',
            name='status',
            field=models.IntegerField(choices=[(1, 'Hero'), (2, 'Villain')], default=1),
            preserve_default=False,
        ),
    ]
