# Generated by Django 4.0.2 on 2022-02-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_heroes_or_villains', '0002_super_type_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_type',
            old_name='status',
            new_name='alignment',
        ),
    ]
