# Generated by Django 4.0.2 on 2022-02-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_heroes_or_villains', '0008_super_type_alignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_type',
            name='alignment',
        ),
        migrations.AlterField(
            model_name='super_type',
            name='id',
            field=models.IntegerField(choices=[(1, 'Hero'), (2, 'Villain')], primary_key=True, serialize=False),
        ),
    ]
