# Generated by Django 4.0.2 on 2022-02-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_heroes_or_villains', '0009_remove_super_type_alignment_alter_super_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_type',
            old_name='alignment_type',
            new_name='alignment',
        ),
    ]
