# Generated by Django 4.0.2 on 2022-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_heroes_or_villains', '0010_rename_alignment_type_super_type_alignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_type',
            old_name='alignment',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='super_type',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
